algoritmo "exercicio1"
// Função : escreva na tela os números de um número inicial a um número final informados pelo usuário.
// Autor : Giovanna Carvalho
// Data : 12/09/2022
// Seção de Declarações 
var
i, f, contador: inteiro

inicio
escreval("Digite o numero inicial:")
leia(i)
escreval("Digite o numero final:")
leia(f)

para contador de i ate f faca
     escreval(contador)
fimpara

fimalgoritmo
