algoritmo "exercicio"
// Função : Faça um programa que receba 5 numeros
// digitados pelo usuário e ao final mostra a soma deles.
// Autor : Giovanna Carvalho
// Data : 23/08/2022
// Seção de Declarações 

var
contador,numero,soma:inteiro
media:real

inicio
para contador de 1 ate 5 faca
  escreval("Digite um numero: ")
  leia(numero)
  soma <- soma + numero
fimpara
escreval("A soma é: ",soma)
media <- soma/5
escreval("A média é: ",media)

fimalgoritmo
